---
coverage:
  status:
    project:
      default:
        target: auto
        removed_code_behavior: removals_only
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "src/lib.rs"
  - "examples/**"
